---
name: AntiXBLExploit
version: 0.0.1
main: CortexPE\AntiXBLExploit\Main
api: 3.0.0
permissions:
  axx:
    description: "Root permission"
    default: false
    children:
      axx.clear:
        description: "Allows usage of /axxclear command"
        default: op
commands:
  axxclear:
    description: "Clear XUID log for specific player"
    permission: "axx.clear"
    usage: "/axxclear <player>"
...
